### ISSUE TITLE
Reviewing the Grassoppers protocol - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#10]
Hi @open-sci/the-leftovers-2-0,

As anticipated in the [lectures on Wednesday (practical part)](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you have to review the [protocol developed by the team Grasshoppers](#6). The two people selected for addressing this task must work independently writing a review and must publish it on [Qeios](https://www.qeios.com), in order to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of both the reviews.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by Alessia438** [comment]
Review by Alessia Cioffi: https://doi.org/10.32388/1PV0Y2
Review by Arianna Moretti: https://doi.org/10.32388/RWNSQC
