### ISSUE TITLE
Writing and submitting a research article - team Grasshoppers

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#14]
Hi @open-sci/grasshoppers,

As anticipated in [yesterday's lecture (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to write a scientific article that presents your research. Please, follow the structure suggested in the [slides linked above](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing) (i.e. Abstract, Introduction, Material and Methods, Result, Discussion and Conclusions, References).

Once finalised, the article should be submitted in Zenodo adding appropriate metadata (the more, the better). The deadline for the submission is two days before the final workshop, i.e. by the 3rd of May, 23:59 Rome time. Once in Zenodo, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the article.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by arcangelo7** [comment]
http://doi.org/10.5281/zenodo.4734513
