### ISSUE TITLE
Revised version of the protocol - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#16]
Hi @open-sci/the-leftovers-2-0,

As anticipated in [yesterday's lecture (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to revise your protocol published on Protocols.io according to the reviews received by the members of the other team. Once your revision of the workflow is finalised, please publish it using the Protocols.io interface. 

In addition, you must also write and publish a response letter to the reviewers, where you explain either how you have addressed their comments or the justification for not having addressed them (please remember that if the latter applies, then your justifications must be very robust). Once finalised, the response letter must be published in Zenodo, and it should explicitly link and mention (even in the metadata) the reviews received, the old version of the protocol and the revised one.

Then, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the revision of the protocol and of the response letter. The deadline to provide all this information is the 28th of April.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by saroppini** [comment]
Updated version of the protocol (still not the final one for the workshop though): 
Nooshin Shahidzadeh, Alessia Cioffi, Arianna Moretti, Sara Coppini 2021. Investigating Invalid DOIs in COCI. protocols.io
https://dx.doi.org/10.17504/protocols.io.buhjnt4n


This is the clickable DOI URL of the response letter: http://doi.org/10.5281/zenodo.4725899

**Comment by saroppini** [comment]
Last version of the protocol:
Sara Coppini, Nooshin Shahidzadeh, Alessia Cioffi, Arianna Moretti 2021. Investigating Invalid DOIs in COCI - Protocol. protocols.io
https://dx.doi.org/10.17504/protocols.io.buqhnvt6
