### ISSUE TITLE
Revised version of DMP - team Grasshoppers

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#18]
Hi @open-sci/grasshoppers,

As anticipated in [yesterday's lecture (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to revise your Data Management Plan (DMP) published on Zenodo according to the reviews received by the members of the other team. The revision of the DMP must be done using an existing service, i.e. [OpenAIRE Argos](https://argos.openaire.eu/). Once your revision of the DMP is finalised, please deposit it in Zenodo (by adding appropriate metadata) in at least a machine-readable format (e.g. JSON) and PDF.

In addition, you must also write and publish a response letter to the reviewers, where you explain either how you have addressed their comments or the justification for not having addressed them (please remember that if the latter applies, then your justifications must be very robust). Once finalised, the response letter must be published in Zenodo, and it should explicitly link and mention (even in the metadata) the reviews received, the old version of the DMP and the revised one.

Then, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of the revision of the DMP and of the response letter. The deadline to provide all this information is the 28th of April.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by denizovski** [comment]
The revised version of **DMP**: [https://doi.org/10.5281/zenodo.4723934](https://doi.org/10.5281/zenodo.4723934) (_The response letter is associated_)
**Response letter** of the review: [https://doi.org/10.5281/zenodo.4723674](https://doi.org/10.5281/zenodo.4723674)

**Comment by sntcristian** [comment]
There is a revised version of the Data Management Plan:
Boente, Ricarda, Massari, Arcangelo, Santini, Cristian, & Tural, Deniz. (2021). Classes of errors in DOI names (Data Management Plan) (Version 4). Zenodo. [https://doi.org/10.5281/zenodo.4733920](https://doi.org/10.5281/zenodo.4733920)
