### ISSUE TITLE
First version of DMP - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#2]
Hi @open-sci/the-leftovers-2-0,

As anticipated in [today's lecture (practical part)](https://docs.google.com/presentation/d/1NabMeG_OAxv6AoBLvHMTO0jMPXYSqznkvud7D0Jjg1k/edit#slide=id.gcbb39b4500_0_0), you have to create the first version of your Data Management Plan (DMP). The DMP should include at least the description of two datasets, i.e. one for the data you will gather and another for the software you will develop to analyse such data. Of course, if you think you need more than two datasets, please do not hesitate to add more.

The creation of the DMP must be done using an existing service, i.e. [OpenAIRE Argos](https://argos.openaire.eu). You should use your ORCID credentials to access it. In case you do not have an ORCID, please visit the [ORCID website](https://orcid.org/) and create a new account. In case you have some doubts about how to use the tool and what to fill in, please watch the recording of [today's lecture (1 April 2021)](https://github.com/open-sci/2020-2021) available in Microsoft Teams.

Once your first version of the DMP is finalised, please deposit it in Zenodo (by adding appropriate metadata) in at least a machine-readable format (e.g. JSON) and PDF. Then, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the first version of the DMP.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by NoonShin** [comment]
https://doi.org/10.5281/zenodo.4671487
