### ISSUE TITLE
Updating the abstract - team Grasshoppers

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#20]
Hi @open-sci/grasshoppers,

As anticipated in [Thursday's lecture (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to update the abstract you wrote and uploaded in the GitHub repository of the course with more precise and additional information derived from the study you have conducted so far (which includes also the information collected in the DMP and in the protocol).

Once finalised, the abstract must be included in the [research article](#14) you have to prepare and submit by the 3rd of May, 23:59 Rome time. However, please update the abstract before writing the article, and every time you have either new or more precise information to share.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by Adracir** [comment]
Updated version with knowledge about results and better overview over the whole work.
