### ISSUE TITLE
Updating the abstract - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#21]
Hi @open-sci/the-leftovers-2-0,

As anticipated in [Thursday's lecture (practical part)](https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing), you have to update the abstract you wrote and uploaded in the GitHub repository of the course with more precise and additional information derived from the study you have conducted so far (which includes also the information collected in the DMP and in the protocol).

Once finalised, the abstract must be included in the [research article](#15) you have to prepare and submit by the 3rd of May, 23:59 Rome time. However, please update the abstract before writing the article, and every time you have either new or more precise information to share.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by ariannamorettj** [comment]
We will update it by the end of the day for sure. Thank you for the reminder!
________________________________
Da: Silvio Peroni ***@***.***>
Inviato: venerdì 23 aprile 2021 07:28
A: open-sci/2020-2021 ***@***.***>
Cc: Arianna Moretti - ***@***.*** ***@***.***>; Team mention ***@***.***>
Oggetto: [open-sci/2020-2021] Updating the abstract - team The Leftovers 2.0 (#21)


Hi @open-sci/the-leftovers-2-0<https://github.com/orgs/open-sci/teams/the-leftovers-2-0>,

As anticipated in Thursday's lecture (practical part)<https://docs.google.com/presentation/d/1QFTaIfCRATf8EFRvanRz67U4xHpb8zw5FUeEpSwJd20/edit?usp=sharing>, you have to update the abstract you wrote and uploaded in the GitHub repository of the course with more precise and additional information derived from the study you have conducted so far (which includes also the information collected in the DMP and in the protocol).

Once finalised, the abstract must be included in the research article you have to prepare and submit by the 3rd of May, 23:59 Rome time. However, please update the abstract before writing the article, and every time you have either new or more precise information to share.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by ariannamorettj** [comment]
We updated the abstract after the DMP revision and the software realization. Now it reflects the final version of the project and both the primary aspects we addressed and the further additions we decided to include during the development phases.
