### ISSUE TITLE
Submitting the software - team Grasshoppers

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#22]
Hi @open-sci/grasshoppers,

As anticipated in the [lecture on the 15th of April (practical part)](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_3), once finalised, the [software you developed](https://github.com/open-sci/2020-2021-grasshoppers-code) must be assigned with a DOI via Zenodo.

Once in Zenodo, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the software. The version specified here must be also the one cited in the [research article](#14) to write.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by arcangelo7** [comment]
http://doi.org/10.5281/zenodo.4734013
