### ISSUE TITLE
Submitting the presentation - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#25]
Hi @open-sci/the-leftovers-2-0,

As anticipated in the [lecture on the 28th of April (practical part)](https://docs.google.com/presentation/d/1USObdYTaujrTikkRtqZlJ8zXh3C91dBezCxdTuskvi4/edit#slide=id.gd3972084b6_0_0), once finalised, the slides supporting your presentation must be uploaded on Zenodo, in order to get a DOI to refer to them, by the 13:00 of 5 May 2021.

Once in Zenodo, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the slides. Please remind to specify, in the title slide (the very first one), all the members of the group and the related roles each member has had in the context of the project, using the [CRediT – Contributor Roles Taxonomy](https://casrai.org/credit/), accompany each of the roles with a brief description of what has been done.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by Alessia438** [comment]
This is the link of the presentation: http://doi.org/10.5281/zenodo.4738716
