### ISSUE TITLE
Adding bibliographic reference of the slides in material.md - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#27]
Hi @open-sci/the-leftovers-2-0,

As anticipated in the [lecture on the 28th of April (practical part)](https://docs.google.com/presentation/d/1USObdYTaujrTikkRtqZlJ8zXh3C91dBezCxdTuskvi4/edit#slide=id.gd3972084b6_0_0), after your presentation on the 5th of May 2021, you have to update your [`material.md`](https://github.com/open-sci/2020-2021/blob/master/docs/TheLeftovers20/material.md) file with the bibliographic reference (in APA style) of your slides deposited in Zenodo.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by Alessia438** [comment]
We updated our material.md with the information about the slides.
