### ISSUE TITLE
Creation of material.md - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#29]
Hi @open-sci/the-leftovers-2-0,

As anticipated in the [lecture on the 28th of April (practical part)](https://docs.google.com/presentation/d/1USObdYTaujrTikkRtqZlJ8zXh3C91dBezCxdTuskvi4/edit#slide=id.gd3972084b6_0_0), in the [space dedicated to your group](https://github.com/open-sci/2020-2021/tree/master/docs/TheLeftovers20) in the repository of the course, you have to create a [`material.md`](https://github.com/open-sci/2020-2021/blob/master/docs/TheLeftovers20/material.md) file where you list all the members of the group with all the roles they have had in the project (using the [CRediT taxonomy](https://casrai.org/credit/) as specified in the title page of [your slides](#25)). 

In addition, in the `material.md` file, you also need to add a bibliographic reference in APA style for each of the items to submit. You can follow the template below to create the document (the words between angular brackets must be substituted with the correct value):

```
# Material - team <<name of the team>>

## Members
[<<Member 1 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...

[<<Member 2 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...

[<<Member 3 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...

[<<Member 4 full name>>](<<GitHub account URL>>), roles:
* <<role 1>>, <<description 1>>
* <<role 2>>, <<description 2>>
* ...


## Material

### Data Management Plan
<<Bibliographic reference in APA style of the last version>>

Reviews of the [<<initial version of the DMP>>](<<DOI URL of the initial version of the DMP>>):
* <<Bibliographic reference in APA style of the first review>>
* <<Bibliographic reference in APA style of the second review>>

Authors' response to the reviews:
* <<Bibliographic reference in APA style of the authors' response to the reviews>>


### Protocol introducing the methodology
<<Bibliographic reference in APA style of the last version>>

Reviews of the [<<initial version of the protocol>>](<<DOI URL of the initial version of the protocol>>):
* <<Bibliographic reference in APA style of the first review>>
* <<Bibliographic reference in APA style of the second review>>

Authors' response to the reviews:
* <<Bibliographic reference in APA style of the authors' response to the reviews>>


### Software developed
<<Bibliographic reference in APA style of the last version>>


### The data gathered while running the methodology
<<Bibliographic reference in APA style of the last version>>


### Article presenting the research
<<Bibliographic reference in APA style of the last version>>


### Slides supporting the presentation
<<Bibliographic reference in APA style of the last version>>
```

Please remember that the last point (i.e. "Slides supporting the presentation") can be added **after** the workshop on the 5th of May. 

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by saroppini** [comment]
The material.md file for the Leftovers team has been created in 2020-2021-the-leftovers-20-code repository: https://github.com/open-sci/2020-2021-the-leftovers-20-code/blob/main/material.md

**Comment by saroppini** [comment]
The material.md file for the Leftovers team has been created in 2020-2021-the-leftovers-20-code repository: https://github.com/open-sci/2020-2021-the-leftovers-20-code/blob/main/material.md

**Comment by essepuntato** [comment]
It should be put in the main course repo. Can you move it there, please?

**Comment by Alessia438** [comment]
Yes, now we have added the file to the course repo.
