### ISSUE TITLE
First version of the protocol - team The Leftovers 2.0

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#5]
Hi @open-sci/the-leftovers-2-0,

As anticipated in [today's lecture (practical part)](https://docs.google.com/presentation/d/1ODujBmeKCJmIBqZlzVBPioU_LPYaospnKs7CxQ0W_Ww/edit?usp=sharing), you have to create the first version of your workflow using [Protocols.io](https://protocols.io/). It must be created within the Protocols.io workspace "Open Science 2020/2021" that has been shared with you (via the invitation link) on Signal. Please, click on such a link to be added as members of the workspace and then log in to Protocols.io using your ORCID.

The workflow should describe how you are going to address the research question related to your project. In particular, you 
should focus on the steps to follow to produce your output data (including explicit mentions to existing data and methods reused) and how these will be then analysed (e.g. by indicating which statistical tool or visualisation you will adopt) to answer your research question.

Once your first version of the workflow is finalised, please publish it using the Protocols.io interface. Then, close this issue by attaching in the comment the clickable DOI URL (https://doi.org/...) of the first version of the workflow.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by NoonShin** [comment]
Here's the link to the first version of the protocol: [dx.doi.org/10.17504/protocols.io.bt5xnq7n](dx.doi.org/10.17504/protocols.io.bt5xnq7n)
