### ISSUE TITLE
Reviewing the Leftovers 2.0 protocol - team Grasshoppers

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2020-2021#9]
Hi @open-sci/grasshoppers,

As anticipated in the [lectures on Wednesday (practical part)](https://docs.google.com/presentation/d/1Y6CdDwgcuQpRJBDbSDDbDBXULCWljCGSnsgn_FU0hPs/edit#slide=id.gd0ba9f17f0_0_142), two of you have to review the [protocol developed by the team The Leftovers 2.0](#5). The two people selected for addressing this task must work independently writing a review and must publish it on [Qeios](https://www.qeios.com), in order to get a DOI for it. A reminder: once the review is published and a DOI is obtained, the review cannot be modified anymore.

Once both your reviews are published, close this issue by attaching in the comment the clickable DOI URLs (https://doi.org/...) of both the reviews.

For further doubts, do not hesitate to contact me in the Signal group.

**Comment by denizovski** [comment]
1) Review of: Investigating Invalid DOIs in COCI v1 by **_Deniz Tural_** [https://doi.org/10.32388/WHWOI8](https://doi.org/10.32388/WHWOI8)
2) Review of: Investigating Invalid DOIs in COCI v1 by _**Arcangelo Massari**_ [https://doi.org/10.32388/X2DX81](https://doi.org/10.32388/X2DX81)
